services:
  dev-database:
    image: postgres:17.5
    container_name: ecom-devices
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sontontk269
      POSTGRES_DB: ecom-devices
    networks:
      - nestjs-network

  redis:
    image: redis:latest
    container_name: ecom-redis
    ports:
      - 6379:6379
    networks:
      - nestjs-network
    environment:
      REDIS_PASSWORD: Sontontk269

networks:
  nestjs-network:
